### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by axxapy** [Karasiq/shadowcloud#2]
Nice work!

It would be nice to have Dockerfile && official image in hub.docker.com so it could be deployed to some personal server (like NAS/RasberryPi/VPS/etc)

Only issue I can see now is javafx. It opens Display even if password is provided through configuration file.
It would be nice to have an ability to provide configuration parameters via command line (may be there is already some way?)

Here is basic Dockerfile which supposed to work (after removing opening X display):
````
FROM openjdk:8-jre-alpine

RUN addgroup -S shadowcloud && \
	adduser -h /opt -S -G shadowcloud shadowcloud && \
	apk add --no-cache bash && \
	#install openjfx from https://github.com/sgerrand/alpine-pkg-java-openjfx \
	apk --no-cache add ca-certificates wget && \
	wget --quiet --output-document=/etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
	wget https://github.com/sgerrand/alpine-pkg-java-openjfx/releases/download/8.151.12-r0/java-openjfx-8.151.12-r0.apk && \
	apk add --no-cache java-openjfx-8.151.12-r0.apk
	

ADD shadowcloud /opt

USER shadowcloud

#CMD /opt/bin/shadowcloud-desktop
ENTRYPOINT /opt/bin/shadowcloud-desktop
````
build:
````
#(first, extact shadowcloud into shadowcloud directory)
$ docker build -t karasiq/shadowcloud .
````

Not sure what javafx is used for. If it is used only for asking for password, I would recommend to make it, at least, optional

**Comment by Karasiq** [comment]
Ok, i added the `console-app` build configuration: https://github.com/Karasiq/shadowcloud/commit/fbf3ed65bf0d6f3a8ac415efdb0471d423c0a24a
